services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - dotanet-net

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 1s
      timeout: 10s
      retries: 5
    networks:
      - dotanet-net

  adserver:
    build:
      context: .
      dockerfile: Dockerfile
      target: adserver
    ports:
      - "8081:8081"
    command: [
      "./bin",
      "-adserverurl", "${ADSERVER_URL_PROJECT}",
      "-panelurlads", "${PANEL_URL_INSIDE}",
      "-panelurlpic", "${PANEL_URL_OUTSIDE}",
      "-eventserviceurl", "${EVENTSERVICE_OUTSIDE}",
      "-newAdTreshold", "${NEW_AD_THRESHOLD}",
      "-newAdProb", "${NEW_AD_PROB}",
      "-expAdProb", "${EXP_AD_PROB}"
    ]
    depends_on:
      postgres:
        condition: service_healthy
      panel:
        condition: service_healthy
    container_name: adserver
    networks:
      - dotanet-net

  eventservice:
    build:
      context: .
      dockerfile: Dockerfile
      target: eventservice
    ports:
      - "8082:8082"
    command: [
      "./bin",
      "-dbuser", "${DB_USER}",
      "-dbpassword", "${DB_PASSWORD}",
      "-dbname", "${DB_NAME}",
      "-dbport", "${DB_PORT}",
      "-dbhost", "${DB_HOST}",
      "-eventserviceurl", "${EVENTSERVICE_URL_PROJECT}",
      "-kafkaendpoint", "${KAFKA_ENDPOINT}"
    ]
    depends_on:
      postgres:
        condition: service_healthy

    container_name: eventservice
    networks:
      - dotanet-net

  reporter:
    build:
      context: .
      dockerfile: Dockerfile
      target: reporter
    command: [
      "./bin",
      "-dbuser", "${DB_USER}",
      "-dbpassword", "${DB_PASSWORD}",
      "-dbname", "${DB_NAME}",
      "-dbport", "${DB_PORT}",
      "-dbhost", "${DB_HOST}",
      "-kafkaendpoint", "${KAFKA_ENDPOINT}"
    ]
    depends_on:
      postgres:
        condition: service_healthy
      eventservice:
        condition: service_started
    container_name: reporter
    networks:
      - dotanet-net

  panel:
    build:
      context: .
      dockerfile: Dockerfile
      target: panel
    image: panel
    ports:
      - "8085:8085"
    command: [
      "./bin",
      "-dbuser", "${DB_USER}",
      "-dbpassword", "${DB_PASSWORD}",
      "-dbname", "${DB_NAME}",
      "-dbport", "${DB_PORT}",
      "-dbhost", "${DB_HOST}",
      "-panelurl", "${PANEL_URL_PROJECT}",
      "-adserverurl", "${ADSERVER_URL_OUTSIDE}"
    ]
    depends_on:
      postgres:
        condition: service_healthy
    container_name: panel
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8085/ads/list || exit 1" ]  # Adjust port as needed
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dotanet-net

  publisherwebsite:
    build:
      context: .
      dockerfile: Dockerfile
      target: publisherwebsite
    image: publisherwebsite
    ports:
      - "8084:8084"
    command: [
      "./bin",
      "-publisherservice", "${PUBLISHER_URL_PROJECT}",
      "-panelurl", "${PANEL_URL_OUTSIDE}"
    ]
    depends_on:
      postgres:
        condition: service_healthy
    container_name: publisherwebsite
    networks:
      - dotanet-net

  screper:
    build:
      context: .
      dockerfile: Dockerfile
      target: screper
    image: screper
    ports:
      - "8089:8089"
    command: [
      "./bin",
      "-dbuser", "${DB_USER}",
      "-dbpassword", "${DB_PASSWORD}",
      "-dbname", "${DB_NAME}",
      "-dbport", "${DB_PORT}",
      "-dbhost", "${DB_HOST}",
      "-port","${SCRAPER_PORT}"
    ]
    depends_on:
      postgres:
        condition: service_healthy
      panel:
        condition: service_started
      publisherwebsite:
        condition: service_started
    container_name: screper
    networks:
      - dotanet-net

volumes:
  pgdata:

networks:
  dotanet-net:
    driver: bridge
