version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dotanet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 30s
      timeout: 10s
      retries: 5

  adserver:
    build:
      context: .
      dockerfile: Dockerfile
      target: adserver
    image: adserver
    command: [
      "./adserver",
      "-adserverurl", "0.0.0.0:8081",
      "-panelurl", "http://panel:8085",
      "-eventserviceurl", "http://eventservice:8082",
      "-newAdTreshold", "5",
      "-newAdProb", "0.25",
      "-expAdProb", "0.75"
    ]
    depends_on:
      postgres:
        condition: service_healthy
      panel:
        condition: service_healthy

  eventservice:
    build:
      context: .
      dockerfile: Dockerfile
      target: eventservice
    image: eventservice
    command: [
      "./eventservice",
      "-dbuser", "user",
      "-dbpassword", "password",
      "-dbname", "dotanet",
      "-dbport", "5432",
      "-dbhost", "postgres",
      "-eventserviceurl", "0.0.0.0:8082"
    ]
    depends_on:
      postgres:
        condition: service_healthy
      panel:
        condition: service_healthy

  panel:
    build:
      context: .
      dockerfile: Dockerfile
      target: panel
    image: panel
    ports:
      - "8085:8085"
    command: [
      "./panel",
      "-dbuser", "user",
      "-dbpassword", "password",
      "-dbname", "dotanet",
      "-dbport", "5432",
      "-dbhost", "postgres",
      "-panelurl", "0.0.0.0:8085",
      "-adserverurl", "http://adserver:8081"
    ]
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  publisherwebsite:
    build:
      context: .
      dockerfile: Dockerfile
      target: publisherwebsite
    image: publisherwebsite
    ports:
      - "8084:8084"
    command: [
      "./publisherwebsite",
      "-publisherservice", "0.0.0.0:8084",
      "-panelurl", "http://panel:8085"
    ]
    depends_on:
      postgres:
        condition: service_healthy
      panel:
        condition: service_healthy
      eventservice:
        condition: service_healthy
      adserver:
        condition: service_healthy

volumes:
  pgdata:
