name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [adserver, common, eventservice, panel, publisherwebsite] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.5'

    - name: Build ${{ matrix.module }}
      run: |
        cd ${{ matrix.module }}
        go build -v

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          ${{ github.workspace }}/Dockerfile
          ${{ github.workspace }}/docker-compose.yml
          ${{ github.workspace }}/path/to/other/required/files/
          ${{ matrix.module }}/build/${{ matrix.module }} # Assuming the build output is here

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts

    - name: Copy files to server
      env:
        DEPLOY_USER: ${{ "gambron" }}
        DEPLOY_HOST: ${{ "95.217.125.139" }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        scp -r build-artifacts/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

    - name: Deploy using Docker Compose
      env:
        DEPLOY_USER: ${{ "gambron" }}
        DEPLOY_HOST: ${{ "95.217.125.139" }}
        DEPLOY_PATH: ${{ / }}
      run: |
        ssh $DEPLOY_USER@$DEPLOY_HOST 'cd $DEPLOY_PATH && docker-compose -f docker-compose.yml pull && docker-compose -f docker-compose.yml up -d'
